import OCConnectWrapper from "@/components/connect";
import "./globals.css"; 

export const metadata = {
  title: "Blockchain HQ",
  description: "Generated by Blockchain HQ",
};

export default function RootLayout({ children }) {

  const opts = {
    redirectUri: 'http://localhost:3000/redirect', 
    referralCode: 'PARTNER6',  
  };

  return (
    <html lang="en">
      <body
        className={`antialiased`}
      >
       <OCConnectWrapper opts={opts} sandboxMode={true}>
          {children}
        </OCConnectWrapper>
      </body>
    </html>
  );
}
