 
import "./globals.css"; 
import { WalletProvider } from "@/context/WalletContext";

export const metadata = {
  title: "Blockchain HQ",
  description: "Generated by Blockchain HQ",
};

export default function RootLayout({ children }) {

  const opts = {
    redirectUri: 'http://localhost:3000/redirect', 
    referralCode: 'PARTNER6',  
  };

  return (
    <html lang="en">
      <body
        className={`antialiased`}
      >
        <WalletProvider>
          {children}
          </WalletProvider>
      </body>
    </html>
  );
}
